import type { BalanceRecommendation } from "../../core/src/types.js";
import type { BacktestResult } from "../../balance-engine/src/backtest-engine.js";
import type { WeightSearchResult } from "../../balance-engine/src/weight-search.js";
export function renderShadowReport(dt: string, recs: BalanceRecommendation[], backtests: BacktestResult[], weights: WeightSearchResult[]): string {
  const by=(t:string)=>recs.filter(r=>r.dt===dt && r.recommendationType===t).slice(0,8);
  const section=(title:string, items:BalanceRecommendation[])=>`## ${title}\n`+(items.length?items.map((r)=>`- **${r.entityType}:${r.entityId}** score=${r.score} rank=${r.rank}; evidence: ${r.evidence.map(e=>`${e.label}=${e.value}`).join("; ")}; data quality: ${r.dataQuality.issues.map(i=>i.code).join(", ") || "ok"}`).join("\n"):"- No candidates.")+"\n";
  const warnings=[...new Set(recs.flatMap(r=>r.dataQuality.issues.map(i=>`${i.code}: ${i.message}`)))];
  return `# Daily Balance Shadow Report - ${dt}\n\n## Executive Summary\n- This is a shadow recommendation report for Balance Validation, not automatic action.\n- V0 validates predictive signals only and does not claim causal uplift or budget optimization.\n- Recommendations include evidence, score breakdowns, and data-quality warnings.\n\n${section("加码候选 / Add Candidates",by("add"))}\n${section("降权候选 / Downrank Candidates",by("downrank"))}\n${section("排查候选 / Investigate Candidates",by("investigate"))}\n${section("观察 / Watch List",by("watch"))}\n## Backtest Summary\n${backtests.slice(0,8).map(b=>`- ${b.recommendationType} ${b.horizon}: precision@5=${b.metrics.precisionAtK["5"]?.toFixed(2)}, topDecileLift=${b.metrics.topDecileLift?.toFixed(2) ?? "n/a"}, sample=${b.metrics.sampleCount}`).join("\n")}\n\n## Weight Config Summary\n- Best config: ${weights[0]?.config.configId ?? "n/a"}; objective=${weights[0]?.objectiveScore ?? "n/a"}. ${weights[0]?.reason ?? ""}\n- Candidate configs evaluated: ${weights.length}.\n\n## Data Quality Warnings\n${warnings.length?warnings.map(w=>`- ${w}`).join("\n"):"- No warnings."}\n\n## Methodology Notes\n- At date t, scoring uses only rows available at or before t and evaluates future t+1/t+3/t+7 windows.\n- The report is predictive validation, not causal uplift proof. Holdout experiments/action logs are required before causal claims.\n`;
}
