export type EntityType = "room" | "product" | "carrier" | "ad_account" | "ad_material";
export type CarrierType = "live" | "short_video" | "product_card" | "search" | "other";
export type DataQualitySeverity = "info" | "warning" | "critical";
export type DataQualityIssueCode =
  | "missing_required_field" | "zero_denominator" | "sample_too_small" | "mapping_missing"
  | "finance_discontinuous" | "ad_attribution_missing" | "outlier_clipped" | "unknown";
export interface DataQualityIssue { code: DataQualityIssueCode; severity: DataQualitySeverity; message: string; field?: string; }
export interface DataQuality { usable: boolean; sampleSize?: number; sampleLevel?: "none" | "low" | "medium" | "high"; inventoryUsable?: boolean; profitUsable?: boolean; financeUsable?: boolean; adAttributionUsable?: boolean; issues: DataQualityIssue[]; }
export interface RoomDailyBalanceRow { dt: string; roomId: string; anchorId?: string; anchorName?: string; shopId?: string; payAmt: number; netPayAmt: number; orderCnt: number; payUserCnt: number; cost: number; refundAmt: number; refundRate: number; gmvCostRatio: number | null; gpm?: number | null; liveHours?: number | null; abnormalCount?: number; warningCount?: number; recoveryRateAfterWarning?: number | null; dataQuality: DataQuality; }
export interface ProductLiveBalanceRow { dt: string; roomId: string; productId: string; productName?: string; shopId?: string; productExposure: number; productClick: number; productCtr: number | null; productPayAmt: number; productNetPayAmt: number; productOrderCnt: number; productPayUserCnt: number; productClickDealRate: number | null; productRefundAmt: number; productRefundRate: number | null; exposureShareInRoom?: number | null; payShareInRoom?: number | null; skuId?: string | null; inventoryQty?: number | null; costPrice?: number | null; dataQuality: DataQuality; }
export interface CarrierDailyBalanceRow { dt: string; shopId: string; carrierType: CarrierType; payAmt: number; netPayAmt: number; orderCnt: number; payUserCnt: number; cost?: number; refundAmt?: number; refundRate?: number | null; contributionShare?: number | null; netContributionShare?: number | null; dataQuality: DataQuality; }
export interface AdBalanceRow { dt: string; entityType: "ad_account" | "ad_material"; entityId: string; shopId?: string; cost: number; paidGmv?: number | null; overallPaymentRoi?: number | null; paidOrderCnt?: number | null; followupRoi?: number | null; costShare?: number | null; planId?: null; campaignId?: null; attributionWindow?: null; dataQuality: DataQuality; }
export type BalanceRow = RoomDailyBalanceRow | ProductLiveBalanceRow | CarrierDailyBalanceRow | AdBalanceRow;
export interface FeatureGroupScores { contribution: number; efficiency: number; quality: number; stability: number; growthSpace: number; riskPenalty: number; }
export type RecommendationType = "add" | "maintain" | "downrank" | "investigate" | "watch";
export interface ScoreWeights { contribution: number; efficiency: number; quality: number; stability: number; growthSpace: number; riskPenalty: number; }
export interface ScoringConfig { configId: string; entityType: EntityType; recommendationType: RecommendationType; weights: ScoreWeights; minSampleLevel?: "low" | "medium" | "high"; hardExclusions?: string[]; }
export interface EvidenceItem { label: string; metric?: string; value?: number | string | null; benchmark?: number | string | null; direction?: "positive" | "negative" | "neutral"; explanation: string; }
export interface BalanceRecommendation { dt: string; entityType: EntityType; entityId: string; recommendationType: RecommendationType; score: number; scoreBreakdown: FeatureGroupScores; rank?: number; evidence: EvidenceItem[]; dataQuality: DataQuality; configId: string; }
export interface BalanceOutcome { dt: string; entityType: EntityType; entityId: string; horizon: "1d" | "3d" | "7d"; futureNetPayAmt?: number; futurePayAmt?: number; futureGmvCostRatio?: number | null; futureRefundRate?: number | null; futureRoi?: number | null; futureLowEfficiency?: boolean; futureHighRefund?: boolean; futureTopQuantile?: boolean; futureBottomQuantile?: boolean; }
export interface BacktestMetrics { precisionAtK: Record<string, number>; topDecileLift: number | null; bottomDecileHitRate: number | null; ndcgAtK: Record<string, number>; spearmanRankCorrelation?: number | null; recommendationStability?: number | null; sampleCount: number; }
export interface BalanceActionLogItem { actionTime: string; dt: string; recommendationId: string; entityType: EntityType; entityId: string; recommendationType: RecommendationType; operator?: string; accepted: boolean; actionType?: RecommendationType | "ignore"; actionDetail?: string; reason?: string; }
export interface PostActionEvaluation { recommendationId: string; horizon: "1d" | "3d" | "7d"; beforeMetrics: Record<string, number | null>; afterMetrics: Record<string, number | null>; matchedControlMetrics?: Record<string, number | null>; estimatedLift?: number | null; evaluationNote: string; }
